name: My first workflow
on  : push
jobs:
    first_job:
        runs-on: ubuntu-lastest
        steps:
            - name: welcome message
              run: echo "my first github action job"
            - name: list files
              run: ls
            - name: read file
              run: cat readme.md